version: '3.8'

services:
  app:
    image: my-app
    #build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_USER: joaoT
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: users_db
      REDIS_HOST: redis

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: joaoT
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

volumes:
  mysql-data:
